language: node_js
node_js:
  - '0.10'

install:
  - npm install
  - npm install -g karma-cli
  - npm test

cache:
  directories:
    - node_modules
    - bower_components

after_script:
  - gulp enforce-coverage